spring:
  main:
    log-startup-info: off
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: dbuser
    password: 12345
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-location: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
        jdbc:
          time-zone: UTC

logging:
  level:
    root: INFO
    ru.yandex.practicum.shareit: INFO
    org.zalando.logbook: TRACE
    org.springframework.orm.jpa: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE

logbook.format.style: http
