spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shareit
    username: danijke
    password: 68356835
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect