server:
  port: 9090
spring:
  main:
    log-startup-info: off
    banner-mode: off
  sql:
    init:
      mode: always
      schema-location: classpath:schema.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight_sql: true
        jdbc:
          time-zone: UTC

logging:
  level:
    root: INFO

logbook.format.style: http
